apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-ui
  template:
    metadata:
      labels:
        app: admin-ui
    spec:
      containers:
      - image: gcr.io/forgerock-io/platform-admin-ui/docker-build:7.1.0-877c32740ad5b29ffc9be390ee9ca20d33f90d22
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: platform-config
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: admin-ui
        resources:
          requests:
            memory: "100Mi"
            cpu: "10m"
          limits:
            memory: "100Mi"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
