apiVersion: apps/v1
kind: Deployment
metadata:
  name: end-user-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: end-user-ui
  template:
    metadata:
      labels:
        app: end-user-ui
    spec:
      containers:
      - image: gcr.io/forgerock-io/platform-enduser-ui/docker-build:7.1.0-85c632de8f198510c41bd58724891da05fa70b49
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: platform-config
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: end-user-ui
        resources:
          requests:
            memory: "100Mi"
            cpu: "10m"
          limits:
            memory: "100Mi"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
